openapi: 3.0.0
info:
  title: CredyCheck API Documentation
  description: |

    This document describes methods that are available in CredyCheck API.

    All requests will get responses by a callback that arrives later to your api (could take up to 30 seconds).

    To see callback definitions, please check "Callbacks" tab inside the API method spec.

    # Glossary
     * Requester - a partner who sends any kind of data query to us
     * Responder - a partner from whom we query any kind of data
     * Envelope - encrypted container for personal ID
     * Us - CredyCheck API

    # Workflow
    ![](https://github.com/credy/credycheck-docs/raw/master/round_1.png)
    ![](https://github.com/credy/credycheck-docs/raw/master/round_2.png)

    # Authentication
    CredyCheck API uses OAuth 2.0 with Client Credentials grant type.
    Tokens can be obtained from /v1/token method.

  version: 3.0.0
security:
  - oAuth2: []
paths:
  /v1/start-session:
    post:
      description: |-
        # Start session
        This method is used to get public keys from other partners in order to encrypt an envelope for each of them. It returns the public keys to the callback provided.
      requestBody:
        content:
          application/json:
            schema:
              required:
                - callback_uri
              properties:
                callback_uri:
                  type: string
                  example: 'http://example.com/my_callback'
      responses:
        '202':
          description: Session started
          content:
            application/json:
              schema:
                type: object
                properties:
                  session_uuid:
                    type: string
                    example: b3345507-8298-4bd1-843a-6a968e593f00
      callbacks:
        session_started:
          '{$request.body#/callback_uri}':
            post:
              description: ''
              requestBody:
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/Session'
              responses:
                '202':
                  description: ''
  '/v1/{session_uuid}/get-customer-history':
    post:
      description: ''
      parameters:
        - name: session_uuid
          in: path
          description: ''
          required: true
          schema:
            format: string
            example: b3345507-8298-4bd1-843a-6a968e593f00
      requestBody:
        content:
          application/json:
            schema:
              properties:
                callback_uri:
                  type: string
                  example: 'http://example.com/my_callback'
                envelopes:
                  type: array
                  items:
                    $ref: '#/components/schemas/Envelope'
      responses:
        '202':
          description: ''
      callbacks:
        history_collected:
          '{$request.body#/callback_uri}':
            post:
              description: |
                Aggregated loan history to Requester
              requestBody:
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/CustomerHistory'
              responses:
                '204':
                  description: ''

components:
  schemas:
    Envelope:
      type: object
      required:
        - key
        - envelope
      properties:
        key:
          type: string
          example: b3345507-8298-4bd1-843a-6a968e593f00
          description: "Public key UUID"
        envelope:
          type: string
          example: "encoded personal ID"
          description: "Customer personal ID encrypted with public key"
    CustomerHistory:
      type: object
      required:
        - partner_provided_data_count
        - partner_no_data_count
      properties:
        total_applications_count_30days:
          type: integer
          format: int32
          example: 22
          description: Shows how many applications in total partners have about customer in the last 30 days.
        total_applications_count_5days:
          type: integer
          format: int32
          example: 44
          description: Shows how many applications in total partners have about customer in the last 5  days.
        total_last_submitted_application_date:
          type: string
          example: "2082-07-30"
          description: Shows customer last loan application date among partners.
        total_count_of_active_loans:
          type: integer
          format: int32
          example: 4
          description: Shows how many active loans in total partners have with customer.
        total_count_of_loans_overdue_5_plus:
          type: integer
          format: int32
          example: 7
          description: Shows how many 5+ days overdue loans in total partners have with customer.
        max_lender_applications_count_30days:
          type: integer
          format: int32
          example: 5
          description: Shows how many applications partner has about customer in the last 30 days. Maximum number among partners.
        max_lender_applications_count_5days:
          type: integer
          format: int32
          example: 3
          description: Shows how many applications partner has about customer in the last 5 days. Maximum number among partners.
        max_lender_count_of_active_loans:
          type: integer
          format: int32
          example: 2
          description: Shows how many active loans partner has with customer. Maximum number among partners.
        max_lender_count_of_loans_overdue_5_plus:
          type: integer
          format: int32
          example: 3
          description: Shows how many 5+ days overdue loans partner has with customer. Maximum number among partners.
        partner_provided_data_count:
          type: integer
          format: int32
          example: 12
          description: Shows how many partners responded successfully.
        partner_provided_no_data_count:
          type: integer
          format: int32
          example: 0
          description: Shows how many partners didn't manage to give response within specified timeframe.
        partner_no_customer_count:
          type: integer
          format: int32
          example: 2
          description: Shows how many partners have no info about the customer in their database.
    SessionKey:
      type: object
      required:
        - uuid
        - key
      properties:
        uuid:
          type: string
          example: b3345507-8298-4bd1-843a-6a968e593f00
        key:
          type: string
          example: "public_key_string_goes_here"
    Session:
      type: object
      required:
        - uuid
        - keys
      properties:
        uuid:
          type: string
          example: b3345507-8298-4bd1-843a-6a968e593f00
        keys:
          type: array
          items:
            $ref: '#/components/schemas/SessionKey'


  securitySchemes:
    oAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: '/v1/token'
          scopes: {}

