openapi: 3.0.0
info:
  title: CredyCheck API Documentation
  description: |

    This document describes methods that are available in CredyCheck API.

    All requests will get responses by a callback that arrives later to your api (could take up to 30 seconds).

    To see callback definitions, please check "Callbacks" tab inside the API method spec.

    # Glossary
     * Requester - a partner who sends any kind of data query to us
     * Responder - a partner from whom we query any kind of data
     * Envelope - encrypted container for personal ID
     * Us, we - CredyCheck API

    # Workflow
    ![](https://github.com/credy/credycheck-docs/raw/master/round_1.png)
    ![](https://github.com/credy/credycheck-docs/raw/master/round_2.png)

    # Authentication
    CredyCheck API uses OAuth 2.0 with Client Credentials grant type.
    Tokens can be obtained from /v1/token method.

    # Envelope

    Envelope is JWE token.

    Specs:
    * alg: RSA-OAEP-256
    * enc: A256CBC-HS512

  version: 3.0.0
security:
  - oAuth2: []
paths:
  /v1/start-session:
    post:
      description: |-
        # Start session
        This method is used to get public keys from other partners in order to encrypt an envelope for each of them. It returns the public keys to the callback provided.
      requestBody:
        content:
          application/json:
            schema:
              required:
                - callback_uri
              properties:
                callback_uri:
                  type: string
                  example: 'http://example.com/my_callback'
                  description: The url where we will send session_started callback. (see Callbacks tab of this method).
      responses:
        '202':
          description: Session started
          content:
            application/json:
              schema:
                type: object
                properties:
                  session_uuid:
                    type: string
                    example: b3345507-8298-4bd1-843a-6a968e593f00
      callbacks:
        session_started:
          '{$request.body#/callback_uri}':
            post:
              description: ''
              requestBody:
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/Session'
              responses:
                '202':
                  description: ''
  '/v1/{session_uuid}/get-customer-history':
    post:
      description: 'Used to ask for customer data.'
      parameters:
        - name: session_uuid
          in: path
          description: ''
          required: true
          schema:
            format: string
            example: b3345507-8298-4bd1-843a-6a968e593f00
      requestBody:
        content:
          application/json:
            schema:
              properties:
                callback_uri:
                  type: string
                  example: 'http://example.com/my_callback'
                envelopes:
                  type: array
                  description: An array of envelopes. Envelope must be created for each public key received in session_started callback (see POST /v1/start-session for reference).
                  items:
                    $ref: '#/components/schemas/Envelope'
      responses:
        '202':
          description: ''
      callbacks:
        history_collected:
          '{$request.body#/callback_uri}':
            post:
              description: |
                Aggregated loan history to Requester
              requestBody:
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/CustomerHistory'
              responses:
                '204':
                  description: ''

components:
  schemas:
    Envelope:
      type: object
      required:
        - key
        - envelope
      properties:
        key:
          type: string
          example: b3345507-8298-4bd1-843a-6a968e593f00
          description: "Public key UUID that you received from session_started callback (see POST /v1/start-session for reference)."
        envelope:
          type: string
          example: eyJhbGciOiJSU0EtT0FFUC0yNTYiLCJlbmMiOiJBMjU2Q0JDLUhTNTEyIiwiemlwIjoiREVGIn0.zaAWoRog2iR4oG24leaqFypwQmMV9TS1AqHNWYLgFm-Wf_gViB0Hyu6w2N3tRIrjzn98cvdqFMJCpqS8MWpSNdLKvMLDlVAVCdRwFwK-H-kEP3iRLMVfG6eHk8EHSKlDHevYzHNajecSvg4wYW5Wcm7nv_mn1CqHh7_7jsxnLmUKOV-lUhH3vtUGbyhnsJY3rZEsa2VIppVd2LFVcqZzuH6c_r0vsf1Yn_46YC286D6eboEaToUdnH8T2EMsBMzpFq7NQ1wfr-_LG-r8v989l5ZbXv_ASg0bKoPvn2PF-5o9g0q-XzJ7G3qCICsZH55nBxI2EO9w6J7YxKfPUmiiRnVDB6Tuz9ZqHS2cN8rrGQDXaOjpF6J4Sh78rRTdCZ5zHUAvr8IHwmgujwsBq8aQe17m1_b0qdTO3oAs-ssIjwhk-JXAnInkD92CqmX9CiB44MAFJwAznEaB1kSUY5ZNSlhIB_xqykAi9pxBPTWGvo-Jt-l4liapbQfZpEcMpcPN-2DQ_mBZ3aK9l3aXr_SAeFPv3SwS1vuvZT_92USGg98zJ6lu0UUN9jT7MoKqDquofzWsvC4rK3HKsKrSWUU5jJh5Dq6IiDQSMXzDXKRjKHUYkn7dvuO88Q_FvcoENPJLJXrIJlHrY_26tTx-BTwSgMDBbpymn_OyLOJPYRn3moQ.yCmnuyLQzNl91LP9iLmNGA.sGtQ2h7r0Pe79ri3CRHd_QIb_U7DjFlH5dBHgWzzcfA.CtB47h2A-LEHWYOLrpmIplcK-wbkSaMdiAn17s0gh-c
          description: "Customers personal ID encrypted for public key. In JWE format."
    CustomerHistory:
      type: object
      required:
        - partner_provided_data_count
        - partner_no_data_count
        - partner_no_customer_count
      properties:
        total_applications_count_30days:
          type: integer
          format: int32
          example: 22
          description: Shows how many loan applications in total partners have about customer in the last 30 days. Includes only full completed/submitted loan applications (not partial/incomplete).
        total_applications_count_5days:
          type: integer
          format: int32
          example: 44
          description: Shows how many loan applications in total partners have about customer in the last 5 days. Includes only full completed/submitted loan applications (not partial/incomplete).
        total_last_submitted_application_date:
          type: string
          example: "2082-07-30"
          description: Shows customer last completed/submitted loan application date among partners.
        total_count_of_active_loans:
          type: integer
          format: int32
          example: 4
          description: Shows how many active loans in total partners have with customer.
        total_count_of_loans_overdue_5_plus:
          type: integer
          format: int32
          example: 7
          description: Shows how many 5+ days overdue loans in total partners have with customer. Only the ones which principal debt is 8+ € (NOT including interest and other fees) are included.
        max_lender_applications_count_30days:
          type: integer
          format: int32
          example: 5
          description: Shows how many loan applications partner has about customer in the last 30 days. Maximum number among partners. Includes only full completed/submitted loan applications (not partial/incomplete).
        max_lender_applications_count_5days:
          type: integer
          format: int32
          example: 3
          description: Shows how many loan applications partner has about customer in the last 5 days. Maximum number among partners. Includes only full completed/submitted loan applications (not partial/incomplete).
        max_lender_count_of_active_loans:
          type: integer
          format: int32
          example: 2
          description: Shows how many active loans partner has with customer. Maximum number among partners.
        max_lender_count_of_loans_overdue_5_plus:
          type: integer
          format: int32
          example: 3
          description: Shows how many 5+ days overdue loans partner has with customer. Maximum number among partners. Only the ones which principal debt is 8+ € (NOT including interest and other fees) are included.
        partner_provided_data_count:
          type: integer
          format: int32
          example: 12
          description: Shows how many partners responded successfully.
        partner_provided_no_data_count:
          type: integer
          format: int32
          example: 0
          description: Shows how many partners didn't manage to give response within specified timeframe.
        partner_no_customer_count:
          type: integer
          format: int32
          example: 2
          description: Shows how many partners have no info about the customer in their database.
    SessionKey:
      type: object
      required:
        - uuid
        - key
      properties:
        uuid:
          type: string
          example: b3345507-8298-4bd1-843a-6a968e593f00
          description: UUID4 of partner's public key. This is needed later when you send envolope to us.
        key:
          type: string
          example: {"alg":"RSA-OAEP-256","use":"enc","kty":"RSA","n":"z-nCuGVjrSiFQmKq0T4kHSK2LKC62oHVMcILnTgb8WoFtC-yM0C7lu71V5y-5Y_2UXKVItRpsJYr_9_pbjbg-c-dn5G8H8Q1m5JwFQt_szgCH9dsjzSNJG9AD3IR6KjFGB-HErWhJSrcpDo3EKpoktm4RFf9Jb_oVq0i-Yz8729uxCmxNI9GAsTFXiwjKtPcZdaZ6vlMavFuYAQanM2dxdAyObpIp1kfZaSjz2BCtJlp0NoVzT24uN8uDg89GD3_7TaiGoQ1G2niF-GAyLTYGAHwSqVUe1Whfj8PznRHijBs4VEzCcusOUzlC3DmvQq2U_at0OG4V0rg5F7gfRILh4MOXzMinCiAew3BY6Ck1jehtwNzEtg6G4KqOtIP9dltLVNDaiAQQ7V7COw6gH-xGoUCivtGLHnkhTibnFrlZgwYOd5idRI9GC7Y18Pb9M80Eogi6MXlOqo_lD4PlyYQie8Tecu9pIe91CK6VUrQtm1ZbincUqg5_kVBDykHG7wm4l2VmyBkxG-8Hp_I6HpEvI8cCXBDUqKdN_UQz_4HVjpUjXrShfs1-OpNRWsnD38Stm7gLozO3EBw7-CgfUyAcjygrWTaApHFGPH5wfKbKLIJg13PDkhwYv43SsYAYCylNiNEDFf6wpDRE6OVPD1WobQE9brrnuI3nnydxW5mp2U","e":"AQAB"}
          description: Partner's public key.
    Session:
      type: object
      required:
        - uuid
        - keys
      properties:
        uuid:
          type: string
          example: b3345507-8298-4bd1-843a-6a968e593f00
        keys:
          type: array
          items:
            $ref: '#/components/schemas/SessionKey'


  securitySchemes:
    oAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: '/v1/token'
          scopes: {}

