openapi: 3.0.0
info:
  title: CredyCheck API Documentation
  description: |
    # Glossary 
     * Requester - a partner who sends any kind of data query to us 
     * Responder - a partner from whom we query any kind of data 
     * Envelope - encrypted container for personal ID 
     * Us - CredyCheck API 
  version: 3.0.0
security: 
  - oAuth2: []
paths:
  /v1/start-session:
    post:
      description: |-
        # Start session 
        This method is used to get public keys from other partners in order to encrypt an envelope for each of them. It returns the public keys to the callback provided.
      requestBody:
        content:
          application/json:
            schema:
              properties:
                callback_uri:
                  type: string
                  example: 'http://example.com/my_internal_id_maybe/get_keys'
      responses:
        '202':
          description: Session started
          content:
            application/json:
              schema:
                type: object
                properties:
                  session_uuid:
                    type: string
                    example: b3345507-8298-4bd1-843a-6a968e593f00
      callbacks:
        session_started:
          '{$request.body#/callback_uri}':
            post:
              description: ''
              requestBody:
                content:
                  application/json:
                    schema:
                      properties:
                        session_uuid:
                          type: string
                          example: b3345507-8298-4bd1-843a-6a968e593f00
                        keys:
                          type: array
                          items: 
                            type: object
                            properties:
                              key_uuid:
                                type: string
                                example: b3345507-8298-4bd1-843a-6a968e593f00
                              public_key:
                                type: string
                                example: "key_binary_data_goes_here"
              responses:
                '202':
                  description: ''
  '/v1/{session_uuid}/get-customer-history':
    post:
      description: ''
      parameters:
        - name: session_uuid
          in: path
          description: ''
          required: true
          schema:
            format: string
            example: b3345507-8298-4bd1-843a-6a968e593f00
      requestBody:
        content:
          application/json:
            schema:
              properties:
                callback_uri:
                  type: string
                  example: 'http://example.com/my_callback'
                envelopes:                
                  type: array
                  items:
                    type: object
                    properties:
                      key_uuid:
                        type: string
                        example: b3345507-8298-4bd1-843a-6a968e593f00
                      envelope:
                        type: string
                        example: "encoded personal ID"
      responses:
        '202':
          description: ''
      callbacks:
        history_collected:
          '{$request.body#/callback_uri}':
            post:
              description: |
                Aggregated loan history to Requester
              requestBody:
                content:
                  application/json:
                    schema:
                      properties:
                        session_uuid:
                          type: string
                          example: "b3345507-8298-4bd1-843a-6a968e593f00"
                        total_applications_count_30days: 
                          type: integer
                          format: int32
                          example: 22
                        total_applications_count_5days: 
                          type: integer
                          format: int32
                          example: 44
                        total_last_submitted_application_date: 
                          type: string
                          example: "2082-07-30"
                        total_count_of_active_loans: 
                          type: integer
                          format: int32
                          example: 4
                        total_count_of_loans_overdue_5_plus: 
                          type: integer
                          format: int32
                          example: 7
                        max_lender_applications_count_30days: 
                          type: integer
                          format: int32
                          example: 5
                        max_lender_applications_count_5days: 
                          type: integer
                          format: int32
                          example: 3
                        max_lender_count_of_active_loans: 
                          type: integer
                          format: int32
                          example: 2
                        max_lender_count_of_loans_overdue_5_plus: 
                          type: integer
                          format: int32
                          example: 3
              responses:
                '204':
                  description: ''      
components:
  securitySchemes:
    oAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: '/v1/token'
          scopes: {}
          
